version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG_MODE=True
      - LOG_LEVEL=Debug

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
