apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "event-manager.fullname" . }}-frontend-config
data:
  config.json: |-
    {
      "API_URL": "http://{{ include "event-manager.fullname" . }}-backend:{{ .Values.backend.port }}"
    }
