apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-manager.fullname" . }}-secrets
type: Opaque
stringData:
  sqlalchemy-database-uri: {{ printf "mysql+pymysql://%s:%s@%s-mysql/%s" .Values.mysql.auth.username .Values.mysql.auth.password .Release.Name .Values.mysql.auth.database }}
